version: "3.7"
services:

  traefik:
    image: traefik:2.3
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefik.tls.domains[0].main=*.test.local"
        - "traefik.http.routers.traefik.tls.domains[0].sans=test.local"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.middlewares=redirect@file"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.rule=HostHeader(`traefik.test.local`, `www.traefik.test.local`)"
        - "traefik.http.routers.api.middlewares=servicesDefault@file,auth@file"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.services.api.loadbalancer.server.port=8080"
    ports:
      - 80:80
      - 443:443
      - 22:22
    networks:
      - shared
      - services
    configs:
      - traefik.yml
      - traefik.dynamic.yml
    secrets:
      - do_auth_token
      - admin_auth
      - registry_auth
    environment:
      - "DO_AUTH_TOKEN_FILE=/run/secrets/do_auth_token"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/acme.json:/acme.json

  portainer-agent:
    image: portainer/agent:2.0.0
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - agent_network
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      AGENT_PORT: 9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer:2.0.0
    command: -H tcp://portainer-agent:9001 --tlsskipverify
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.rule=HostHeader(`portainer.test.local`, `www.portainer.test.local`)"
        - "traefik.http.routers.portainer.middlewares=servicesDefault@file"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - shared
      - agent_network
    volumes:
      - portainer-data:/data

configs:
  traefik.yml:
    file: ./config/traefik/traefik.yml
  traefik.dynamic.yml:
    file: ./config/traefik/traefik.dynamic.yml

secrets:
  do_auth_token:
    file: ./secrets/do_auth_token.txt
  admin_auth:
    file: ./secrets/htpasswd.admin
  registry_auth:
    file: ./secrets/htpasswd.registry

networks:
  agent_network:
    driver: overlay
    attachable: true
  shared:
    external: true
  services:
    external: true

volumes:
  portainer-data:
    external: true
