http:
  middlewares:
    compression:
      compress: {}
    secureHeaders:
      headers:
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        sslRedirect: true
    corsHeaders:
      headers:
        accessControlMaxAge: 100
        addVaryHeader: true
    authRegistry:
      basicAuth:
        usersFile: "/run/secrets/registry_auth"
        realm: "registry"
    servicesDefault:
      chain:
        middlewares:
          - compression
          - secureHeaders

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
