version: "3.7"
services:

  proxy:
    image: nineseconds/mtg:stable
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.mtg-proxy.entrypoints=websecure"
        - "traefik.tcp.routers.mtg-proxy.rule=HostSNI(`mtg.test.local)"
        - "traefik.tcp.routers.mtg-proxy.tls=true"
        - "traefik.tcp.routers.mtg-proxy.tls.passthrough=true"
        - "traefik.tcp.routers.mtg-proxy.service=mtg-proxy"
        - "traefik.tcp.services.mtg-proxy.loadbalancer.server.port=3128"
    networks:
      - shared
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/mtg/config.toml:/config.toml

networks:
  shared:
    external: true
