version: "3.7"
services:

  stable:
    image: registry.test.local/website:stable
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.rule=HostHeader(`website.local`, `www.website.local`)"
        - "traefik.http.routers.website.middlewares=secureHeaders@file"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.services.website.loadbalancer.server.port=80"
    networks:
      - services

  dev:
    image: registry.website.local/website:latest
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.routers.website-dev.entrypoints=websecure"
        - "traefik.http.routers.website-dev.rule=HostHeader(`dev.website.local`, `www.dev.website.local`)"
        - "traefik.http.routers.website-dev.middlewares=secureHeaders@file,auth@file,ondemand-dev@docker"
        - "traefik.http.routers.website-dev.tls=true"
        - "traefik.http.services.website-dev.loadbalancer.server.port=80"
    networks:
      - services

networks:
  services:
    external: true
