version: "3.7"
services:

  postgres:
    image: postgres:13-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - services
    environment:
      - "POSTGRES_DB"
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "PGDATA=/var/lib/postgresql/13/data"
    volumes:
      - db13-data:/var/lib/postgresql/13/data

networks:
  services:
    external: true

volumes:
  db13-data:
    external: true
